module.exports = {
    TAG_MODEL               : "api::tag.tag",
    USER_MODEL              : "plugin::users-permissions.user",
    BATCH_MODEL             : "api::batch.batch",
    STOCK_MODEL             : "api::stock.stock",
    UNITY_MODEL             : "api::unity.unity",
    PRODUCT_MODEL           : "api::product.product",
    CATEGORY_MODEL          : "api::category.category",
    WAREHOUSE_MODEL         : "api::warehouse.warehouse",
    INVITATION_MODEL        : "api::invitation.invitation",
    AVAILABILITY_MODEL      : "api::availability.availability",
    STOCK_MOVEMENT_MODEL    : "api::stock-movement.stock-movement",
    PRODUCTION_ORDER_MODEL  : "api::production-order.production-order",
    ADJUSTMENT_MOTIVE_MODEL : "api::adjustment-motive.adjustment-motive",
};